image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform
  TF_STATE_NAME: production
  TF_VAR_bucket_name: "resume-site-${CI_PROJECT_ID}-bucket"

cache:
  key: "${TF_STATE_NAME}"
  paths:
    - ${TF_ROOT}/.terraform

before_script:
  - cd ${TF_ROOT}

stages:
  - validate
  - plan
  - deploy
  - cleanup

validate:
  stage: validate
  script:
    - gitlab-terraform validate

plan:
  stage: plan
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

apply:
  stage: deploy
  script:
    - gitlab-terraform apply
    - apk add --no-cache aws-cli
    - aws s3 sync ${CI_PROJECT_DIR} s3://$(gitlab-terraform output -raw s3_bucket_name) --exclude "terraform/*" --exclude ".git/*" --exclude ".gitlab-ci.yml"
  environment:
    name: production
  when: manual

cleanup:
  stage: cleanup
  script:
    - gitlab-terraform destroy
  environment:
    name: production
    action: stop
  when: manual
